services:
  retropie_backup:
    image: retropie_backup:latest
    container_name: retropie_backup
    volumes:
      - /docker/retropie_backup/data:/data
    environment:
      - TZ=America/New_York
      - RETROPIE_HOST=192.168.68.80
      - RETROPIE_USER=pi
      - RETROPIE_PASSWORD=raspberry
    restart: unless-stopped